### ISSUE TITLE
Wrong encoding with Russian .style

### ISSUE THREAD

**Issue by axyzdile** [north-road/slyr#131] opened 2022-05-18 10:26 UTC
Converting style file with russian tags and names creates xml with wrong encoded tags and names.

**To Reproduce**
convert style file with russian tags and names

![wrong tags](https://user-images.githubusercontent.com/64549817/169011008-1ce79bac-2f69-43fc-887b-1f5a1b476d4f.jpg)
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - QGIS release QGIS 3.24.2

**Additional context**
Add any other context about the problem here. Examples of style, result and right result.
[GOST2.style.zip](https://github.com/nyalldawson/slyr/files/8715199/GOST2.style.zip)
[GOST2_converted.xml.zip](https://github.com/nyalldawson/slyr/files/8715202/GOST2_converted.xml.zip)
[GOST2_should_be.xml.zip](https://github.com/nyalldawson/slyr/files/8715261/GOST2_should_be.xml.zip)

I did not recognize what kind of codepage Arcgis uses, so cant help with it. But looks like it is cp1251 LITERALLY converts in UTF-8 or something.

**Comment by nyalldawson** [comment] 2022-07-15 02:14
Honestly, right now I consider broken Russian encoding as a feature, not a bug. Closing as won't fix.

**Closed by nyalldawson** 2022-07-15 02:14 UTC
Labels: bug
